version: '3'
services:
  clash:
    cap_add:
      - NET_ADMIN
    image: rinex20/docker-clash-ui:latest
    volumes:
      - /docker/clash/config.yaml:/root/config.yaml
      - /docker/clash/ss:/etc/shadowsocks-libev
    restart: unless-stopped
    privileged: true
    environment:
      - LOCAL_IP=192.168.90.0/24 #replace to your localnetwork
      - MODE=tproxy
      - SS_ON=0
    networks:
      macnet:
        ipv4_address: 192.168.90.6
    container_name: clash-ss-90.6
    command: ["/usr/local/bin/clash"]

networks:
  macnet:
    external: true
