version: '2.1'
services:
  clash:
    cap_add:
      - NET_ADMIN
    image: rinex20/docker-clash-ui:latest
    volumes:
      - /docker/clash/config.yaml:/root/.config/clash/config.yaml
      - /docker/clash/ss:/etc/shadowsocks-libev
    restart: unless-stopped
    privileged: true
    environment:
      - LOCAL_IP=192.168.90.0/24
      - MODE=tproxy
      - SS_ON=1
    networks:
      vlan:
        ipv4_address: 192.168.90.6
    container_name: clash-ss-90.6
    entrypoint: /usr/local/bin/entrypoint.sh
    command: ["/usr/local/bin/clash"]

networks:
  vlan:
    external:
       name: macnet
